### ISSUE TITLE
Fuel Bug

### ISSUE THREAD

**Issue by UsmanNaeem1703** [dragon-forge/SimpleQuarry#2]
While fueling with a bucket of lava it doesn't give off an empty bucket after using lava like furnace do.

**Comment by Zeitheron** [comment]
Please check your container where the quarry dumps items. Perhaps, it is there.

**Comment by puggan** [comment]
Eat 2 of my buckets today, 
Simple Quarry 21.0.3, 
MC 1.21.1
(in modpack Opolis Inc)
